window.esdocSearchIndex = [
  [
    "@graph-algorithm/maximum-matching/src/adddefaultweight.js~adddefaultweight",
    "function/index.html#static-function-addDefaultWeight",
    "<span>addDefaultWeight</span> <span class=\"search-result-import-path\">@graph-algorithm/maximum-matching/src/addDefaultWeight.js</span>",
    "function"
  ],
  [
    "@graph-algorithm/maximum-matching/src/core/blossom/blossom.js~blossom",
    "function/index.html#static-function-blossom",
    "<span>blossom</span> <span class=\"search-result-import-path\">@graph-algorithm/maximum-matching/src/core/blossom/blossom.js</span>",
    "function"
  ],
  [
    "@graph-algorithm/maximum-matching/src/core/blossom/blossomedges.js~blossomedges",
    "function/index.html#static-function-blossomEdges",
    "<span>blossomEdges</span> <span class=\"search-result-import-path\">@graph-algorithm/maximum-matching/src/core/blossom/blossomEdges.js</span>",
    "function"
  ],
  [
    "@graph-algorithm/maximum-matching/src/core/blossom/blossomleaves.js~blossomleaves",
    "function/index.html#static-function-blossomLeaves",
    "<span>blossomLeaves</span> <span class=\"search-result-import-path\">@graph-algorithm/maximum-matching/src/core/blossom/blossomLeaves.js</span>",
    "function"
  ],
  [
    "@graph-algorithm/maximum-matching/src/core/blossomnochecks.js~blossomnochecks",
    "variable/index.html#static-variable-blossomNoChecks",
    "<span>blossomNoChecks</span> <span class=\"search-result-import-path\">@graph-algorithm/maximum-matching/src/core/blossomNoChecks.js</span>",
    "variable"
  ],
  [
    "@graph-algorithm/maximum-matching/src/core/blossom/checkdelta2.js~checkdelta2",
    "function/index.html#static-function-checkDelta2",
    "<span>checkDelta2</span> <span class=\"search-result-import-path\">@graph-algorithm/maximum-matching/src/core/blossom/checkDelta2.js</span>",
    "function"
  ],
  [
    "@graph-algorithm/maximum-matching/src/core/blossom/checkdelta3.js~checkdelta3",
    "function/index.html#static-function-checkDelta3",
    "<span>checkDelta3</span> <span class=\"search-result-import-path\">@graph-algorithm/maximum-matching/src/core/blossom/checkDelta3.js</span>",
    "function"
  ],
  [
    "@graph-algorithm/maximum-matching/src/core/blossom/endpoints.js~endpoints",
    "function/index.html#static-function-endpoints",
    "<span>endpoints</span> <span class=\"search-result-import-path\">@graph-algorithm/maximum-matching/src/core/blossom/endpoints.js</span>",
    "function"
  ],
  [
    "@graph-algorithm/maximum-matching/src/cardinality/opt/general.js~general",
    "function/index.html#static-function-general",
    "<span>general</span> <span class=\"search-result-import-path\">@graph-algorithm/maximum-matching/src/cardinality/opt/general.js</span>",
    "function"
  ],
  [
    "@graph-algorithm/maximum-matching/src/weight/opt/general.js~general",
    "function/index.html#static-function-general",
    "<span>general</span> <span class=\"search-result-import-path\">@graph-algorithm/maximum-matching/src/weight/opt/general.js</span>",
    "function"
  ],
  [
    "@graph-algorithm/maximum-matching/src/cardinality/approx/general.js~generalapprox",
    "function/index.html#static-function-generalApprox",
    "<span>generalApprox</span> <span class=\"search-result-import-path\">@graph-algorithm/maximum-matching/src/cardinality/approx/general.js</span>",
    "function"
  ],
  [
    "@graph-algorithm/maximum-matching/src/weight/approx/general.js~generalapprox",
    "function/index.html#static-function-generalApprox",
    "<span>generalApprox</span> <span class=\"search-result-import-path\">@graph-algorithm/maximum-matching/src/weight/approx/general.js</span>",
    "function"
  ],
  [
    "@graph-algorithm/maximum-matching/src/iter.js~iter",
    "function/index.html#static-function-iter",
    "<span>iter</span> <span class=\"search-result-import-path\">@graph-algorithm/maximum-matching/src/iter.js</span>",
    "function"
  ],
  [
    "@graph-algorithm/maximum-matching/src/core/blossom/min.js~min",
    "function/index.html#static-function-min",
    "<span>min</span> <span class=\"search-result-import-path\">@graph-algorithm/maximum-matching/src/core/blossom/min.js</span>",
    "function"
  ],
  [
    "@graph-algorithm/maximum-matching/src/core/blossom/neighbours.js~neighbours",
    "function/index.html#static-function-neighbours",
    "<span>neighbours</span> <span class=\"search-result-import-path\">@graph-algorithm/maximum-matching/src/core/blossom/neighbours.js</span>",
    "function"
  ],
  [
    "@graph-algorithm/maximum-matching/src/core/blossom/rotate.js~rotate",
    "function/index.html#static-function-rotate",
    "<span>rotate</span> <span class=\"search-result-import-path\">@graph-algorithm/maximum-matching/src/core/blossom/rotate.js</span>",
    "function"
  ],
  [
    "@graph-algorithm/maximum-matching/src/core/blossom/statistics.js~statistics",
    "function/index.html#static-function-statistics",
    "<span>statistics</span> <span class=\"search-result-import-path\">@graph-algorithm/maximum-matching/src/core/blossom/statistics.js</span>",
    "function"
  ],
  [
    "@graph-algorithm/maximum-matching/src/core/blossom/verifyoptimum.js~verifyoptimum",
    "function/index.html#static-function-verifyOptimum",
    "<span>verifyOptimum</span> <span class=\"search-result-import-path\">@graph-algorithm/maximum-matching/src/core/blossom/verifyOptimum.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/adddefaultweight.js",
    "file/src/addDefaultWeight.js.html",
    "src/addDefaultWeight.js",
    "file"
  ],
  [
    "src/cardinality/approx/bipartite.js",
    "file/src/cardinality/approx/bipartite.js.html",
    "src/cardinality/approx/bipartite.js",
    "file"
  ],
  [
    "src/cardinality/approx/general.js",
    "file/src/cardinality/approx/general.js.html",
    "src/cardinality/approx/general.js",
    "file"
  ],
  [
    "src/cardinality/approx/index.js",
    "file/src/cardinality/approx/index.js.html",
    "src/cardinality/approx/index.js",
    "file"
  ],
  [
    "src/cardinality/index.js",
    "file/src/cardinality/index.js.html",
    "src/cardinality/index.js",
    "file"
  ],
  [
    "src/cardinality/opt/bipartite.js",
    "file/src/cardinality/opt/bipartite.js.html",
    "src/cardinality/opt/bipartite.js",
    "file"
  ],
  [
    "src/cardinality/opt/general.js",
    "file/src/cardinality/opt/general.js.html",
    "src/cardinality/opt/general.js",
    "file"
  ],
  [
    "src/cardinality/opt/index.js",
    "file/src/cardinality/opt/index.js.html",
    "src/cardinality/opt/index.js",
    "file"
  ],
  [
    "src/core/blossom/blossom.js",
    "file/src/core/blossom/blossom.js.html",
    "src/core/blossom/blossom.js",
    "file"
  ],
  [
    "src/core/blossom/blossomedges.js",
    "file/src/core/blossom/blossomEdges.js.html",
    "src/core/blossom/blossomEdges.js",
    "file"
  ],
  [
    "src/core/blossom/blossomleaves.js",
    "file/src/core/blossom/blossomLeaves.js.html",
    "src/core/blossom/blossomLeaves.js",
    "file"
  ],
  [
    "src/core/blossom/checkdelta2.js",
    "file/src/core/blossom/checkDelta2.js.html",
    "src/core/blossom/checkDelta2.js",
    "file"
  ],
  [
    "src/core/blossom/checkdelta3.js",
    "file/src/core/blossom/checkDelta3.js.html",
    "src/core/blossom/checkDelta3.js",
    "file"
  ],
  [
    "src/core/blossom/endpoints.js",
    "file/src/core/blossom/endpoints.js.html",
    "src/core/blossom/endpoints.js",
    "file"
  ],
  [
    "src/core/blossom/index.js",
    "file/src/core/blossom/index.js.html",
    "src/core/blossom/index.js",
    "file"
  ],
  [
    "src/core/blossom/min.js",
    "file/src/core/blossom/min.js.html",
    "src/core/blossom/min.js",
    "file"
  ],
  [
    "src/core/blossom/neighbours.js",
    "file/src/core/blossom/neighbours.js.html",
    "src/core/blossom/neighbours.js",
    "file"
  ],
  [
    "src/core/blossom/rotate.js",
    "file/src/core/blossom/rotate.js.html",
    "src/core/blossom/rotate.js",
    "file"
  ],
  [
    "src/core/blossom/statistics.js",
    "file/src/core/blossom/statistics.js.html",
    "src/core/blossom/statistics.js",
    "file"
  ],
  [
    "src/core/blossom/verifyoptimum.js",
    "file/src/core/blossom/verifyOptimum.js.html",
    "src/core/blossom/verifyOptimum.js",
    "file"
  ],
  [
    "src/core/blossomnochecks.js",
    "file/src/core/blossomNoChecks.js.html",
    "src/core/blossomNoChecks.js",
    "file"
  ],
  [
    "src/core/index.js",
    "file/src/core/index.js.html",
    "src/core/index.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/iter.js",
    "file/src/iter.js.html",
    "src/iter.js",
    "file"
  ],
  [
    "src/weight/approx/bipartite.js",
    "file/src/weight/approx/bipartite.js.html",
    "src/weight/approx/bipartite.js",
    "file"
  ],
  [
    "src/weight/approx/general.js",
    "file/src/weight/approx/general.js.html",
    "src/weight/approx/general.js",
    "file"
  ],
  [
    "src/weight/approx/index.js",
    "file/src/weight/approx/index.js.html",
    "src/weight/approx/index.js",
    "file"
  ],
  [
    "src/weight/index.js",
    "file/src/weight/index.js.html",
    "src/weight/index.js",
    "file"
  ],
  [
    "src/weight/opt/bipartite.js",
    "file/src/weight/opt/bipartite.js.html",
    "src/weight/opt/bipartite.js",
    "file"
  ],
  [
    "src/weight/opt/general.js",
    "file/src/weight/opt/general.js.html",
    "src/weight/opt/general.js",
    "file"
  ],
  [
    "src/weight/opt/index.js",
    "file/src/weight/opt/index.js.html",
    "src/weight/opt/index.js",
    "file"
  ]
]